-- H2-compatible schema for Vehicle Operations demo
-- Mirrors the SQL Server schema but uses H2/ANSI SQL syntax

CREATE TABLE IF NOT EXISTS vehicle (
    vehicle_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin                 VARCHAR(17) NOT NULL UNIQUE,
    model_year           INT NOT NULL,
    model_code           VARCHAR(10) NOT NULL,
    model_name           VARCHAR(50) NOT NULL,
    trim_level           VARCHAR(20),
    engine_code          VARCHAR(15),
    transmission_type    VARCHAR(10),
    plant_code           VARCHAR(5) NOT NULL,
    assembly_date        TIMESTAMP,
    ship_date            TIMESTAMP,
    dealer_code          VARCHAR(10),
    current_mileage      INT DEFAULT 0,
    warranty_start_date   TIMESTAMP,
    warranty_end_date     TIMESTAMP,
    status              VARCHAR(20) DEFAULT 'IN_PRODUCTION',
    created_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_station (
    station_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_code         VARCHAR(15) NOT NULL,
    station_name         VARCHAR(50) NOT NULL,
    plant_code           VARCHAR(5) NOT NULL,
    sequence_order       INT NOT NULL,
    cycle_time_minutes    DECIMAL(8,2),
    is_quality_gate       BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS production_tracking (
    tracking_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id           INT NOT NULL,
    station_id           INT NOT NULL,
    entry_time           TIMESTAMP NOT NULL,
    exit_time            TIMESTAMP,
    operator_id          VARCHAR(20),
    status              VARCHAR(20) DEFAULT 'IN_STATION',
    defects_found        INT DEFAULT 0,
    notes               VARCHAR(500),
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(vehicle_id),
    FOREIGN KEY (station_id) REFERENCES production_station(station_id)
);

CREATE SEQUENCE IF NOT EXISTS claim_number_seq START WITH 100;

CREATE TABLE IF NOT EXISTS warranty_claim (
    claim_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number         VARCHAR(20) NOT NULL UNIQUE,
    vehicle_id           INT NOT NULL,
    dealer_code          VARCHAR(10) NOT NULL,
    claim_date           TIMESTAMP NOT NULL,
    mileage_at_claim      INT NOT NULL,
    symptom_code         VARCHAR(10),
    causal_part_number    VARCHAR(25),
    labor_operation_code  VARCHAR(15),
    labor_hours          DECIMAL(6,2),
    labor_rate           DECIMAL(8,2),
    parts_cost           DECIMAL(10,2),
    sublet_cost          DECIMAL(10,2) DEFAULT 0,
    deductible          DECIMAL(8,2) DEFAULT 0,
    total_amount         DECIMAL(10,2),
    coverage_type        VARCHAR(20),
    claim_status         VARCHAR(15) DEFAULT 'SUBMITTED',
    denial_reason_code    VARCHAR(10),
    approved_date        TIMESTAMP,
    settled_date         TIMESTAMP,
    submitted_by         VARCHAR(50),
    version              INT DEFAULT 0 NOT NULL,
    created_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(vehicle_id)
);

CREATE TABLE IF NOT EXISTS warranty_coverage (
    coverage_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_type        VARCHAR(20) NOT NULL,
    model_year           INT NOT NULL,
    months_from_sale      INT NOT NULL,
    mileage_limit        INT NOT NULL,
    description         VARCHAR(100),
    deductible_amount    DECIMAL(8,2) DEFAULT 0,
    part_group_codes      VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS labor_rate_schedule (
    rate_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code          VARCHAR(10) NOT NULL,
    dealer_tier          VARCHAR(5) NOT NULL,
    labor_type           VARCHAR(20) NOT NULL,
    hourly_rate          DECIMAL(8,2) NOT NULL,
    effective_date       TIMESTAMP NOT NULL,
    expiration_date      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS part (
    part_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number          VARCHAR(25) NOT NULL UNIQUE,
    description         VARCHAR(100) NOT NULL,
    part_group_code       VARCHAR(10),
    unit_cost            DECIMAL(10,2),
    list_price           DECIMAL(10,2),
    weight              DECIMAL(8,3),
    unit_of_measure       VARCHAR(5) DEFAULT 'EA',
    status              VARCHAR(15) DEFAULT 'ACTIVE',
    superseded_by_part_no  VARCHAR(25),
    supplier_code        VARCHAR(20),
    lead_time_days        INT,
    min_order_qty         INT DEFAULT 1,
    created_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS part_fitment (
    fitment_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number          VARCHAR(25) NOT NULL,
    model_code           VARCHAR(10) NOT NULL,
    model_year_from       INT NOT NULL,
    model_year_to         INT NOT NULL,
    trim_level           VARCHAR(20),
    engine_code          VARCHAR(15),
    notes               VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS part_inventory (
    inventory_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number          VARCHAR(25) NOT NULL,
    warehouse_code       VARCHAR(10) NOT NULL,
    on_hand_qty           INT DEFAULT 0,
    reorder_point        INT DEFAULT 0,
    last_count_date       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier (
    supplier_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code        VARCHAR(20) NOT NULL UNIQUE,
    supplier_name        VARCHAR(100) NOT NULL,
    contact_name         VARCHAR(50),
    region              VARCHAR(10),
    country             VARCHAR(30),
    quality_rating       VARCHAR(5),
    is_approved          BOOLEAN DEFAULT TRUE,
    certification_expiry TIMESTAMP,
    annual_volume        INT,
    on_time_delivery_pct  DECIMAL(5,2),
    defect_ppm           INT,
    created_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier_shipment (
    shipment_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code        VARCHAR(20) NOT NULL,
    purchase_order_no     VARCHAR(20),
    part_number          VARCHAR(25) NOT NULL,
    ship_date            TIMESTAMP NOT NULL,
    received_date        TIMESTAMP,
    ordered_qty          INT NOT NULL,
    received_qty         INT,
    rejected_qty         INT DEFAULT 0,
    due_date             TIMESTAMP NOT NULL,
    is_on_time            BOOLEAN,
    inspection_result    VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS dealer_settlement (
    settlement_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_batch_no   VARCHAR(20) NOT NULL,
    dealer_code          VARCHAR(10) NOT NULL,
    claim_id             INT,
    labor_amount         DECIMAL(10,2),
    parts_amount         DECIMAL(10,2),
    parts_markup         DECIMAL(10,2),
    sublet_amount        DECIMAL(10,2),
    deductible_credit    DECIMAL(8,2) DEFAULT 0,
    net_amount           DECIMAL(10,2),
    settlement_date      TIMESTAMP,
    payment_status       VARCHAR(15) DEFAULT 'PENDING',
    FOREIGN KEY (claim_id) REFERENCES warranty_claim(claim_id)
);
